package daemon

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// tmux mode (ContextPRO fork): a local_directory task runs as an interactive
// Claude Code session inside a tmux session in the user's folder. This file
// holds the pieces that need no tmux to test: names, the run script, the
// per-task state file and the transcript tail. See tmux_exec.go for the tmux
// commands and the bottom of this file for the runner and watch loop.

const (
	// tmuxTasksDirName lives directly under WorkspacesRoot. Dot-prefixed on
	// purpose: runGC skips every dot directory as daemon-internal.
	tmuxTasksDirName        = ".tmux-tasks"
	tmuxTranscriptTailLines = 200
	tmuxStateFile           = "tmux.json"
)

// tmuxPollInterval is a var so tests can poll fast.
var tmuxPollInterval = 2 * time.Second

func tmuxTaskDir(workspacesRoot, taskID string) string {
	return filepath.Join(workspacesRoot, tmuxTasksDirName, taskID)
}

var tmuxNameUnsafe = regexp.MustCompile(`[^a-z0-9-]+`)

// tmuxSessionName builds `ctx-<issue identifier>-<task id prefix>`, lower-cased
// and reduced to [a-z0-9-] (tmux rejects "." and ":" in targets), with -2, -3,
// … appended while exists() reports a collision.
func tmuxSessionName(issueIdentifier, taskID string, exists func(string) bool) string {
	ident := strings.ToLower(strings.TrimSpace(issueIdentifier))
	if ident == "" {
		ident = "task"
	}
	short := taskID
	if len(short) > 4 {
		short = short[:4]
	}
	base := tmuxNameUnsafe.ReplaceAllString("ctx-"+ident+"-"+strings.ToLower(short), "-")
	base = strings.Trim(base, "-")
	name := base
	for n := 2; exists(name); n++ {
		name = fmt.Sprintf("%s-%d", base, n)
	}
	return name
}

// shellQuote wraps s in single quotes for /bin/sh, escaping embedded quotes.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// renderTmuxRunScript is what the tmux session executes. It is a script rather
// than a tmux command string so quoting stays sane and the exit code can be
// captured: the session ends when the script ends, and the watch loop reads the
// exit-code file to decide complete vs fail. The prompt comes from a file so a
// multi-kilobyte task brief never has to survive tmux's command parsing.
func renderTmuxRunScript(folder, claudePath string, args []string, promptPath, exitCodePath string) string {
	quoted := make([]string, 0, len(args)+1)
	quoted = append(quoted, shellQuote(claudePath))
	for _, a := range args {
		quoted = append(quoted, shellQuote(a))
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by the ContextPRO daemon for one task. Safe to delete once the task ended.\n")
	b.WriteString("cd " + shellQuote(folder) + " || { echo 127 > " + shellQuote(exitCodePath) + "; exit 127; }\n")
	b.WriteString(strings.Join(quoted, " ") + ` "$(cat ` + shellQuote(promptPath) + `)"` + "\n")
	b.WriteString("code=$?\n")
	b.WriteString(`echo "$code" > ` + shellQuote(exitCodePath) + "\n")
	b.WriteString(`exit "$code"` + "\n")
	return b.String()
}

// tmuxState is written next to the run script so a restarted daemon can adopt
// the session (see adoptTmuxSessions).
type tmuxState struct {
	Session        string    `json:"session"`
	TaskID         string    `json:"task_id"`
	IssueID        string    `json:"issue_id"`
	Folder         string    `json:"folder"`
	WorkDir        string    `json:"work_dir"`
	EnvRoot        string    `json:"env_root"`
	TranscriptPath string    `json:"transcript_path"`
	ExitCodePath   string    `json:"exit_code_path"`
	StartedAt      time.Time `json:"started_at"`
}

func writeTmuxState(dir string, st tmuxState) error {
	data, err := json.MarshalIndent(st, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, tmuxStateFile), data, 0o600)
}

func readTmuxState(dir string) (tmuxState, error) {
	var st tmuxState
	data, err := os.ReadFile(filepath.Join(dir, tmuxStateFile))
	if err != nil {
		return st, err
	}
	if err := json.Unmarshal(data, &st); err != nil {
		return st, fmt.Errorf("tmux state %s: %w", dir, err)
	}
	return st, nil
}

// readTmuxExitCode returns (code, true, nil) when the run script recorded an
// exit code, (0, false, nil) when the file does not exist yet, and an error
// when the file exists but is not an integer.
func readTmuxExitCode(path string) (int, bool, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	code, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return 0, false, fmt.Errorf("exit code file %s: %w", path, err)
	}
	return code, true, nil
}

// ansiEscapePattern covers CSI sequences (colours, cursor moves), OSC
// sequences (titles, hyperlinks) and character-set selects, plus carriage
// returns, which a terminal transcript is full of.
var ansiEscapePattern = regexp.MustCompile(`\x1b\[[0-9;?]*[ -/]*[@-~]|\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)|\x1b[()][0-9A-Za-z]|\r`)

// transcriptTail returns the last `lines` lines of the pane transcript with
// terminal escapes stripped. A missing or unreadable transcript yields "".
func transcriptTail(path string, lines int) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	ring := make([]string, 0, lines)
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		line := ansiEscapePattern.ReplaceAllString(scanner.Text(), "")
		if len(ring) == lines {
			ring = ring[1:]
		}
		ring = append(ring, line)
	}
	return strings.Join(ring, "\n") + "\n"
}
