package daemon

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/multica-ai/multica/server/internal/daemon/execenv"
	"github.com/multica-ai/multica/server/pkg/agent"
)

// tmux mode (ContextPRO fork): a local_directory task runs as an interactive
// Claude Code session inside a tmux session in the user's folder. This file
// holds the pieces that need no tmux to test: names, the run script, the
// per-task state file and the transcript tail. See tmux_exec.go for the tmux
// commands and the bottom of this file for the runner and watch loop.

const (
	// tmuxTasksDirName lives directly under WorkspacesRoot. Dot-prefixed on
	// purpose: runGC skips every dot directory as daemon-internal.
	tmuxTasksDirName        = ".tmux-tasks"
	tmuxTranscriptTailLines = 200
	tmuxStateFile           = "tmux.json"
)

// tmuxPollInterval is a var so tests can poll fast.
var tmuxPollInterval = 2 * time.Second

func tmuxTaskDir(workspacesRoot, taskID string) string {
	return filepath.Join(workspacesRoot, tmuxTasksDirName, taskID)
}

var tmuxNameUnsafe = regexp.MustCompile(`[^a-z0-9-]+`)

// tmuxSessionName builds `ctx-<issue identifier>-<task id prefix>`, lower-cased
// and reduced to [a-z0-9-] (tmux rejects "." and ":" in targets), with -2, -3,
// … appended while exists() reports a collision.
func tmuxSessionName(issueIdentifier, taskID string, exists func(string) bool) string {
	ident := strings.ToLower(strings.TrimSpace(issueIdentifier))
	if ident == "" {
		ident = "task"
	}
	short := taskID
	if len(short) > 4 {
		short = short[:4]
	}
	base := tmuxNameUnsafe.ReplaceAllString("ctx-"+ident+"-"+strings.ToLower(short), "-")
	base = strings.Trim(base, "-")
	name := base
	for n := 2; exists(name); n++ {
		name = fmt.Sprintf("%s-%d", base, n)
	}
	return name
}

// shellQuote wraps s in single quotes for /bin/sh, escaping embedded quotes.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// renderTmuxRunScript is what the tmux session executes. It is a script rather
// than a tmux command string so quoting stays sane and the exit code can be
// captured: the session ends when the script ends, and the watch loop reads the
// exit-code file to decide complete vs fail. The prompt comes from a file so a
// multi-kilobyte task brief never has to survive tmux's command parsing.
func renderTmuxRunScript(folder, claudePath string, args []string, promptPath, exitCodePath string) string {
	quoted := make([]string, 0, len(args)+1)
	quoted = append(quoted, shellQuote(claudePath))
	for _, a := range args {
		quoted = append(quoted, shellQuote(a))
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by the ContextPRO daemon for one task. Safe to delete once the task ended.\n")
	b.WriteString("cd " + shellQuote(folder) + " || { echo 127 > " + shellQuote(exitCodePath) + "; exit 127; }\n")
	b.WriteString(strings.Join(quoted, " ") + ` "$(cat ` + shellQuote(promptPath) + `)"` + "\n")
	b.WriteString("code=$?\n")
	b.WriteString(`echo "$code" > ` + shellQuote(exitCodePath) + "\n")
	b.WriteString(`exit "$code"` + "\n")
	return b.String()
}

// tmuxState is written next to the run script so a restarted daemon can adopt
// the session (see adoptTmuxSessions).
type tmuxState struct {
	Session        string    `json:"session"`
	TaskID         string    `json:"task_id"`
	IssueID        string    `json:"issue_id"`
	Folder         string    `json:"folder"`
	WorkDir        string    `json:"work_dir"`
	EnvRoot        string    `json:"env_root"`
	TranscriptPath string    `json:"transcript_path"`
	ExitCodePath   string    `json:"exit_code_path"`
	StartedAt      time.Time `json:"started_at"`
}

func writeTmuxState(dir string, st tmuxState) error {
	data, err := json.MarshalIndent(st, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, tmuxStateFile), data, 0o600)
}

func readTmuxState(dir string) (tmuxState, error) {
	var st tmuxState
	data, err := os.ReadFile(filepath.Join(dir, tmuxStateFile))
	if err != nil {
		return st, err
	}
	if err := json.Unmarshal(data, &st); err != nil {
		return st, fmt.Errorf("tmux state %s: %w", dir, err)
	}
	return st, nil
}

// readTmuxExitCode returns (code, true, nil) when the run script recorded an
// exit code, (0, false, nil) when the file does not exist yet, and an error
// when the file exists but is not an integer.
func readTmuxExitCode(path string) (int, bool, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	code, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return 0, false, fmt.Errorf("exit code file %s: %w", path, err)
	}
	return code, true, nil
}

// ansiEscapePattern covers CSI sequences (colours, cursor moves), OSC
// sequences (titles, hyperlinks) and character-set selects, plus carriage
// returns, which a terminal transcript is full of.
var ansiEscapePattern = regexp.MustCompile(`\x1b\[[0-9;?]*[ -/]*[@-~]|\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)|\x1b[()][0-9A-Za-z]|\r`)

// transcriptTail returns the last `lines` lines of the pane transcript with
// terminal escapes stripped. A missing or unreadable transcript yields "".
func transcriptTail(path string, lines int) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	ring := make([]string, 0, lines)
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		line := ansiEscapePattern.ReplaceAllString(scanner.Text(), "")
		if len(ring) == lines {
			ring = ring[1:]
		}
		ring = append(ring, line)
	}
	return strings.Join(ring, "\n") + "\n"
}

func (d *Daemon) tmuxController() (tmuxController, error) {
	if d.tmux != nil {
		return d.tmux, nil
	}
	ctl, err := newExecTmux()
	if err != nil {
		return nil, err
	}
	d.tmux = ctl
	return ctl, nil
}

// runTmuxTask is the tmux-mode counterpart of executeAndDrain. The folder has
// already been prepared by execenv.Prepare (brief, MCP config, sidecars), so
// this only has to launch the interactive session and wait for it to end.
func (d *Daemon) runTmuxTask(ctx context.Context, task Task, env *execenv.Environment, assignment *localDirectoryAssignment, claudePath string, opts agent.ExecOptions, prompt string, taskLog *slog.Logger) (TaskResult, error) {
	ctl, err := d.tmuxController()
	if err != nil {
		return TaskResult{}, err
	}
	dir := tmuxTaskDir(d.cfg.WorkspacesRoot, task.ID)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return TaskResult{}, fmt.Errorf("tmux task dir: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(dir) }

	promptPath := filepath.Join(dir, "prompt.md")
	if err := os.WriteFile(promptPath, []byte(prompt), 0o600); err != nil {
		cleanup()
		return TaskResult{}, fmt.Errorf("write tmux prompt: %w", err)
	}
	mcpPath := ""
	if agent.HasManagedMcpConfig(opts.McpConfig) {
		mcpPath = filepath.Join(dir, "mcp.json")
		if err := os.WriteFile(mcpPath, opts.McpConfig, 0o600); err != nil {
			cleanup()
			return TaskResult{}, fmt.Errorf("write tmux mcp config: %w", err)
		}
	}
	exitPath := filepath.Join(dir, "exit-code")
	transcript := filepath.Join(dir, "transcript.log")
	args := agent.BuildClaudeInteractiveArgs(opts, mcpPath, d.logger)
	scriptPath := filepath.Join(dir, "run.sh")
	if err := os.WriteFile(scriptPath, []byte(renderTmuxRunScript(assignment.AbsPath, claudePath, args, promptPath, exitPath)), 0o700); err != nil {
		cleanup()
		return TaskResult{}, fmt.Errorf("write tmux run script: %w", err)
	}

	name := tmuxSessionName(task.IssueIdentifier, task.ID, func(n string) bool {
		alive, err := ctl.HasSession(ctx, n)
		return err == nil && alive
	})
	st := tmuxState{
		Session: name, TaskID: task.ID, IssueID: task.IssueID, Folder: assignment.AbsPath,
		WorkDir: env.WorkDir, EnvRoot: env.RootDir, TranscriptPath: transcript, ExitCodePath: exitPath,
		StartedAt: time.Now().UTC(),
	}
	if err := writeTmuxState(dir, st); err != nil {
		cleanup()
		return TaskResult{}, fmt.Errorf("write tmux state: %w", err)
	}
	if err := ctl.NewSession(ctx, name, assignment.AbsPath, []string{"sh", scriptPath}); err != nil {
		cleanup()
		return TaskResult{}, err
	}
	// Non-fatal: without the pipe the session still runs; only the final
	// transcript tail is lost, and the log says so.
	if err := ctl.PipePane(ctx, name, transcript); err != nil {
		taskLog.Warn("tmux: pipe-pane failed; run output will not be captured", "session", name, "error", err)
	}
	taskLog.Info("tmux: interactive session started", "session", name, "folder", assignment.AbsPath)
	d.announceTmuxSession(ctx, task.ID, name)
	return d.watchTmuxSession(ctx, ctl, st, taskLog)
}

// announceTmuxSession tells the issue where to attach. Nil client in tests.
func (d *Daemon) announceTmuxSession(ctx context.Context, taskID, session string) {
	if d.client == nil {
		return
	}
	text := fmt.Sprintf("Interactive session on %s: `tmux attach -t %s`", d.cfg.DeviceName, session)
	_ = d.client.ReportProgress(ctx, taskID, text, 1, 2)
	_ = d.client.ReportTaskMessages(ctx, taskID, []TaskMessageData{{Seq: 1, Type: "text", Content: text}})
}

// watchTmuxSession polls until the session is gone, then maps the recorded
// exit code to a result. On cancellation it distinguishes a cancelled TASK
// (kill the session) from a daemon shutdown (leave it; adoptTmuxSessions picks
// it up on the next start): if the daemon's root context is done, so is every
// task context, and killing then would destroy the user's live terminal.
func (d *Daemon) watchTmuxSession(ctx context.Context, ctl tmuxController, st tmuxState, taskLog *slog.Logger) (TaskResult, error) {
	ticker := time.NewTicker(tmuxPollInterval)
	defer ticker.Stop()
	for {
		alive, err := ctl.HasSession(ctx, st.Session)
		if err != nil {
			taskLog.Warn("tmux: has-session failed; retrying", "session", st.Session, "error", err)
		} else if !alive {
			return tmuxOutcome(st)
		}
		select {
		case <-ctx.Done():
			if d.rootCtx != nil && d.rootCtx.Err() != nil {
				taskLog.Info("tmux: daemon shutting down; leaving session for adoption", "session", st.Session)
			} else if killErr := ctl.KillSession(context.Background(), st.Session); killErr != nil {
				taskLog.Warn("tmux: kill-session after task cancel failed", "session", st.Session, "error", killErr)
			}
			return TaskResult{}, ctx.Err()
		case <-ticker.C:
		}
	}
}

// tmuxOutcome turns an ended session into the task's result and removes the
// task dir. The user's folder is never touched here.
func tmuxOutcome(st tmuxState) (TaskResult, error) {
	dir := filepath.Dir(st.ExitCodePath)
	defer os.RemoveAll(dir)
	tail := transcriptTail(st.TranscriptPath, tmuxTranscriptTailLines)
	code, found, err := readTmuxExitCode(st.ExitCodePath)
	switch {
	case err != nil:
		return TaskResult{}, fmt.Errorf("interactive session %s: %w", st.Session, err)
	case !found:
		return TaskResult{}, fmt.Errorf("interactive session %s ended without an exit code (session lost)\n\n%s", st.Session, tail)
	case code != 0:
		return TaskResult{}, fmt.Errorf("interactive session %s exited with code %d\n\n%s", st.Session, code, tail)
	}
	return TaskResult{
		Status:  "completed",
		Comment: fmt.Sprintf("Interactive session %s finished.\n\n%s", st.Session, tail),
		WorkDir: st.WorkDir,
		EnvRoot: st.EnvRoot,
	}, nil
}

// adoptTmuxSessions re-attaches to tmux-mode tasks that were running when the
// previous daemon process stopped. The tmux sessions themselves survive a
// daemon restart; only the watcher died. For each recorded task: a live session
// is watched again; a finished one is settled from its exit-code file; one with
// no session and no exit code is failed as lost. Runs once at startup.
func (d *Daemon) adoptTmuxSessions(ctx context.Context) {
	root := filepath.Join(d.cfg.WorkspacesRoot, tmuxTasksDirName)
	entries, err := os.ReadDir(root)
	if err != nil {
		return // nothing recorded (or no root yet)
	}
	ctl, err := d.tmuxController()
	if err != nil {
		d.logger.Warn("tmux: cannot adopt sessions, tmux unavailable", "error", err, "pending", len(entries))
		return
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		dir := filepath.Join(root, entry.Name())
		st, err := readTmuxState(dir)
		if err != nil {
			d.logger.Warn("tmux: dropping unreadable task state", "dir", dir, "error", err)
			_ = os.RemoveAll(dir)
			continue
		}
		go func(st tmuxState) {
			log := d.logger.With("task_id", st.TaskID, "tmux_session", st.Session)
			log.Info("tmux: adopting session from a previous daemon run")
			result, err := d.watchTmuxSession(ctx, ctl, st, log)
			if ctx.Err() != nil {
				return // shutting down again; the state file stays for the next start
			}
			d.reportAdoptedTmuxOutcome(ctx, st, result, err)
		}(st)
	}
}

func (d *Daemon) reportAdoptedTmuxOutcome(ctx context.Context, st tmuxState, result TaskResult, err error) {
	if d.tmuxAdoptionReport != nil {
		d.tmuxAdoptionReport(st, result, err)
		return
	}
	if d.client == nil {
		return
	}
	report := terminalTaskReport{kind: terminalTaskReportComplete, taskID: st.TaskID, output: result.Comment, workDir: st.WorkDir}
	if err != nil {
		report = terminalTaskReport{kind: terminalTaskReportFail, taskID: st.TaskID, errorMessage: err.Error(), workDir: st.WorkDir}
	}
	if rerr := d.reportTerminalTask(ctx, report); rerr != nil {
		// A task the server already closed (cancelled while we were down) lands
		// here; nothing more to do than say so.
		d.logger.Warn("tmux: reporting adopted session outcome failed", "task_id", st.TaskID, "error", rerr)
	}
}
